export type IconStrings =
  | "ArrowRight"
  | "ArrowLeft"
  | "Close"
  | "Calendar"
  | "ChevronDown"
  | "Cog"
  | "HorizontalDots"
  | "Plus"
  | "Logout"
  | "Moon"
  | "Sun"
  | "Selector"
  | "Trash"
  | "VerticalDots";
